# Generated by Django 5.0.3 on 2024-03-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_user_profile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="profile",
            field=models.ImageField(default=None, upload_to="uploads"),
        ),
    ]
