# Generated by Django 5.0.3 on 2024-03-16 19:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_userprofile_alter_user_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                blank=True, default=django.utils.timezone.now, upload_to="uploads/"
            ),
            preserve_default=False,
        ),
    ]
