# Generated by Django 5.0.3 on 2024-03-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_alter_userprofile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="recipes",
            field=models.ManyToManyField(blank=True, to="accounts.recipe"),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
