# Generated by Django 5.0.3 on 2024-03-16 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_user_is_staff"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="recipes",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="recipes",
            field=models.ManyToManyField(blank=True, to="accounts.recipe"),
        ),
    ]
