# Generated by Django 4.2.11 on 2024-03-25 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_user_email_alter_userprofile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='recipes',
        ),
        migrations.AddField(
            model_name='user',
            name='recipes',
            field=models.ManyToManyField(blank=True, to='accounts.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='description',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
